version: 2.1

references:
  - &CERT_KEY certs-cache-{{ checksum "certs_cache_key" }}-v3

setup: true

filters: &all_tags
  tags:
    only: /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    machine: true
    resource_class: mongo/ose  # Specify self-hosted runner for the setup job
    steps:
      - checkout
      - maybe_build_certs
      - run:
          name: Install jq
          command: sudo apt-get update && sudo apt-get install -y jq 
      - run:
          name: Generate config
          command: |
            tools/circle-generate-config.sh generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml

  build:
    machine: true
    resource_class: mongo/ose  # Specify self-hosted runner for the build job
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            make build
      - run:
          name: Run tests
          command: |
            make test

  deploy:
    machine: true
    resource_class: mongo/ose  # Specify self-hosted runner for the deploy job
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: |
            ./deploy.sh

commands:
  maybe_build_certs:
    steps:
      - run:
          name: Prepare cache key
          command: tools/make-certs-cache-key.sh > certs_cache_key && cat certs_cache_key
      - restore_cache:
          name: Restore certificates
          key: *CERT_KEY
      - run:
          name: Build certificates if not cached
          command: test -f tools/ssl/mongooseim/key.pem || make certs
      - run:
          name: Print cert hashes for debugging
          command: find tools/ssl -type f -exec md5sum {} \; | sort
      - run:
          name: Continue if certificate exists
          command: test -f tools/ssl/mongooseim/key.pem
      - save_cache:
          name: Cache built certs
          key: *CERT_KEY
          paths:
            - ~/project/tools/ssl/ca
            - ~/project/tools/ssl/ca-clients
            - ~/project/tools/ssl/mongooseim

workflows:
  setup_and_build:
    jobs:
      - setup:
          filters: *all_tags
      - build:
          requires:
            - setup
          filters: *all_tags
      - deploy:
          requires:
            - build
          filters: *all_tags
